[project]
name = "myenv"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "keyboard>=0.13.5",
    "pillow>=11.2.1",
    "pygetwindow>=0.0.9",
    "pyserial>=3.5",
]
